stages:
  - build
  - test
  
build:
    stage: build
    script:
        - echo $CI_JOB_STAGE
        - mkdir build
        - touch build/info.txt

test:
    stage: test
    script:
        - echo  $CI_JOB_STAGE
        - test -f "build/info.txt"
